### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by search654321** [jest-community/jest-watch-typeahead#99] opened 2021-10-25 11:56 UTC
When I try to add this plugin I get the following error

```
Error: Failed to initialize watch plugin "node_modules/jest-watch-typeahead/filename.js":

  ● Test suite failed to run

    Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/work/my_app/node_modules/jest-watch-typeahead/filename.js
    require() of ES modules is not supported.
    require() of /Users/work/my_app/node_modules/jest-watch-typeahead/filename.js from /Users/work/my_app/node_modules/@jest/core/build/watch.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
    Instead rename filename.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/work/my_app/node_modules/jest-watch-typeahead/package.json.

      at watch (node_modules/@jest/core/build/watch.js:352:34)
      at runWatch (node_modules/@jest/core/build/cli/index.js:455:31)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:407:13)
```

This is my current config
```
module.exports = {
	preset: 'jest-expo',
	watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
};
```

And I'm using v14.18.1

What should I do to fix this issue?

**Comment by mikehdt** [comment] 2021-11-08 01:40
Are you using npm? I've been testing with a project that uses npm that throws this, but yarn seems to be happy. This could just be a coincidence though.

**Comment by SimenB** [comment] 2021-11-08 12:59
You need to use Jest 27. If you're using v27 already, please include a reproduction

**Comment by vsubbotskyy** [comment] 2021-11-23 22:38
I have the same issue, works with version 0.6.5 though

**Comment by ellipticaldoor** [comment] 2021-11-23 22:45
Yeah, downgrading makes the trick

**Comment by SimenB** [comment] 2021-11-24 09:57
Using Jest 27? v1 does not support jest 26 and down

**Comment by SimenB** [comment] 2021-11-24 09:58
E.g. OP is using `jest-expo` which comes with Jest 26, and thus doesn't support v1 of this module

**Comment by jwandekoken** [comment] 2021-12-03 14:23
We are having this issue here too. Using Jest v27.1.0. Downgrading to v0.6.4 made it work.

**Comment by SimenB** [comment] 2022-02-16 20:44
Nobody has posted a reproduction, so I'll close this. Feel free to open a new issue with a reproduction

**Closed by SimenB** 2022-02-16 20:44 UTC
