### ISSUE TITLE
Interesting issue in macOS terminal

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [jest-community/jest-watch-typeahead#8] opened 2018-05-31 02:35 UTC
The first character seems to be cut off:

<img width="450" alt="screen shot 2018-05-30 at 10 34 38 pm" src="https://user-images.githubusercontent.com/25586630/40758094-a6b3f38c-6459-11e8-9adf-f4a6c34900cb.png">
<img width="659" alt="screen shot 2018-05-30 at 10 34 54 pm" src="https://user-images.githubusercontent.com/25586630/40758099-b00a354a-6459-11e8-82b1-6e72836bdd4c.png">

Jest 23.1.0 & latest of this plugin
macOS latest

**Comment by evan-scott-zocdoc** [comment] 2018-05-31 02:43
Tested in hyper on the same computer and can't reproduce, so seems to be something specifically with `Terminal.app`

**Comment by SimenB** [comment] 2018-05-31 06:07
I cannot reproduce in Terminal.

Which shell do you use?

**Comment by evan-scott-zocdoc** [comment] 2018-05-31 06:47
Vanilla bash. I’ll try on another computer and see if it’s some artifact of my setup

**Comment by rogeliog** [comment] 2019-03-14 03:28
This was fixed by https://github.com/jest-community/jest-watch-typeahead/pull/21

**Closed by rogeliog** 2019-03-14 03:28 UTC
