### ISSUE TITLE
Getting error using v1 in a nextjs/typescript project 

### ISSUE THREAD

**Issue by DanielPe05** [jest-community/jest-watch-typeahead#98] opened 2021-10-21 02:57 UTC
When running this out of the box I see the following error:

```
Error: Failed to initialize watch plugin "node_modules/jest-watch-typeahead/filename.js":

  ● Test suite failed to run

    file:///Users/**/**/**/node_modules/jest-watch-typeahead/build/file_name_plugin/prompt.js:4
    import { PatternPrompt, printPatternCaret, printRestoredPatternCaret } from 'jest-watcher';
                            ^^^^^^^^^^^^^^^^^
    SyntaxError: Named export 'printPatternCaret' not found. The requested module 'jest-watcher' is a CommonJS module, which may not support all module.exports as named exports.
    CommonJS modules can always be imported via the default export, for example using:

    import pkg from 'jest-watcher';
    const { PatternPrompt, printPatternCaret, printRestoredPatternCaret } = pkg;

      at async requireOrImportModule (node_modules/jest-util/build/requireOrImportModule.js:65:32)
      at async watch (node_modules/@jest/core/build/watch.js:337:34)
      at async _run10000 (node_modules/@jest/core/build/cli/index.js:311:7)
      at async runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
```

this is what my jest config looks like: 
```
module.exports = {
  roots: ['<rootDir>', '<rootDir>/src'],
  collectCoverageFrom: [
    '**/*.{js,jsx,ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**'
  ],
  moduleNameMapper: {
    /* Handle CSS imports (with CSS modules)
    https://jestjs.io/docs/webpack#mocking-css-modules */
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',

    '.+\\.(css|styl|less|sass|scss|jpg|jpeg|png|svg|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      'jest-transform-stub',

    // Handle module aliases
    '^@/(.*)$': '<rootDir>/src/$1'
  },
  testPathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/.next/'],
  testEnvironment: 'jsdom',
  transform: {
    /* Use babel-jest to transpile tests with the next/babel preset
    https://jestjs.io/docs/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object */
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }]
  },
  testMatch: ['**/tests/unit/**/*.spec.[jt]s?(x)'],
  transformIgnorePatterns: [
    '/node_modules/',
    '^.+\\.module\\.(css|sass|scss)$',
    '[/\\\\]node_modules[/\\\\].+\\.(ts|tsx)$'
  ],
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname'
  ],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'json', 'jsx']
}
```

and the relevant dependencies:
```
    "next": "^11.1.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
    "babel-jest": "^27.3.1",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.3.1",
    "jest-transform-stub": "^2.0.0",
    "jest-watch-typeahead": "^1.0.0",
    "typescript": "^4.4.4"
```

Curious if this is something you are aware of or have a workaround for? I've tried to find other examples using v1 with this next setup using `babel-jest` and the `next/babel` preset but couldn't find any. I tried removing the `{ presets: ['next/babel'] }` to see if that was causing the issue but no luck there either... Any help here is appreciated. 🙇🏻

**Comment by DanielPe05** [comment] 2021-10-21 13:08
Hey, thank you for the quick rrsponse!
Using node `v14.16.1`, not sure how to prevent this from happening since this was a fresh installation and as you can see in the jest config I'm not doing anything out of the ordinary other than using the babel preset for nextjs, but even without that I still see the issue :/

**Comment by yads** [comment] 2021-11-23 22:44
So I think the issue is that the jest-watcher module doesn't support the named imports. See https://simonplend.com/node-js-now-supports-named-imports-from-commonjs-modules-but-what-does-that-mean/

Updating the build output files `build/file_name_plugin/prompt.js` and `build/test_name_plugin/prompt.js` to have the following code

```
import jestWatcher from 'jest-watcher';
const { PatternPrompt, printPatternCaret, printRestoredPatternCaret } = jestWatcher;
```

I think this commit is causing the issue https://github.com/jest-community/jest-watch-typeahead/commit/a8e6940851e7eefe16b69113fb29c6bd36916bb8#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0 I think the module option needs to be reverted until jest and its plugins update to using ES2020 modules (https://github.com/facebook/jest/blob/main/tsconfig.json)

**Comment by MkMan** [comment] 2022-01-12 23:00
I had the same issue when using node `v14.15.4`, updating to `v14.18.3` fixed it.

**Comment by SimenB** [comment] 2022-02-16 20:46
Not seeing anyone using a supported version of node report any issue, so I'll close this.

Anyone using a supported node rang and with a minimal reproduction, feel free to open up a new issue.

https://github.com/jest-community/jest-watch-typeahead/blob/bed8a2af5c47f8005ceb689e9cd3353466e2fade/package.json#L96

**Closed by SimenB** 2022-02-16 20:46 UTC
